spring:
  application:
    name: homepage-eureka

server:
  port: 8000

eureka:
  instance:
    hostname: localhost
  client:
    # 表示是否从 Eureka Server 中获取注册信息，默认true， 单点eureka server 不需要同步其他节点数据，所以配置false
    fetch-registry: false
    # 是否将自己注册到 Eureka Server, 默认true， 单点不需要注册自己
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
